GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGF1bCIsImlhdCI6MTcwNDkwNjU5MiwiZXhwIjoxNzA0OTA2NjI3fQ.MjolXscxYyFAUGpmKSwhce6T6PP-ZLdeGrTh0rIu9vk

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Paul"
}

####

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGF1bCIsImlhdCI6MTcwNDkwNjU1MH0.db4yIY2f0m2M_ANPCBq_FlUF41q3oo4Pb6kss0xVCBo"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGF1bCIsImlhdCI6MTcwNDcyNDAwN30.Xmtv4hSSzegcbhGyjRQHmY7slCo-bjdjHAhzKHgVNn4"
}